//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ID { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> ID_SUBJECT { get; set; }
        public string CAU_TRA_LOI { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
