//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public string NameDocument { get; set; }
        public string PathDocument { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual CategoryDocument CategoryDocument { get; set; }
        public virtual CategoryDocument CategoryDocument1 { get; set; }
        public virtual CategoryDocument CategoryDocument2 { get; set; }
    }
}
