//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HouzingEntities : DbContext
    {
        public HouzingEntities()
            : base("name=HouzingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountLog> AccountLogs { get; set; }
        public virtual DbSet<Anh> Anhs { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Lich_Dat_Phong> Lich_Dat_Phong { get; set; }
        public virtual DbSet<MenuItemFunction> MenuItemFunctions { get; set; }
        public virtual DbSet<QuanLyAnhVideo> QuanLyAnhVideos { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VIDEO> VIDEOs { get; set; }
        public virtual DbSet<Quan_Ly_Ghi_No> Quan_Ly_Ghi_No { get; set; }
        public virtual DbSet<CategoryDocument> CategoryDocuments { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Quan_Ly_Chi_Phi> Quan_Ly_Chi_Phi { get; set; }
    
        public virtual int ApplicationUserRoles_DeleteItem(Nullable<long> userId, Nullable<int> roleID)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApplicationUserRoles_DeleteItem", userIdParameter, roleIDParameter);
        }
    
        public virtual int ApplicationUserRoles_InsertItem(Nullable<long> userId, Nullable<int> roleID)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApplicationUserRoles_InsertItem", userIdParameter, roleIDParameter);
        }
    
        public virtual int MenuItemRoles_DeleteByRoleID(Nullable<int> iDRole)
        {
            var iDRoleParameter = iDRole.HasValue ?
                new ObjectParameter("IDRole", iDRole) :
                new ObjectParameter("IDRole", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MenuItemRoles_DeleteByRoleID", iDRoleParameter);
        }
    
        public virtual int MenuItemRoles_InsertItem(string menuItem_ID, Nullable<int> role_ID)
        {
            var menuItem_IDParameter = menuItem_ID != null ?
                new ObjectParameter("MenuItem_ID", menuItem_ID) :
                new ObjectParameter("MenuItem_ID", typeof(string));
    
            var role_IDParameter = role_ID.HasValue ?
                new ObjectParameter("Role_ID", role_ID) :
                new ObjectParameter("Role_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MenuItemRoles_InsertItem", menuItem_IDParameter, role_IDParameter);
        }
    
        public virtual ObjectResult<Users_SelectUsersNoRole_Result> Users_SelectUsersNoRole(Nullable<int> iDRole)
        {
            var iDRoleParameter = iDRole.HasValue ?
                new ObjectParameter("IDRole", iDRole) :
                new ObjectParameter("IDRole", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Users_SelectUsersNoRole_Result>("Users_SelectUsersNoRole", iDRoleParameter);
        }
    
        public virtual ObjectResult<qlchiphi_select_item_ngaytao_exact_Result> qlchiphi_select_item_ngaytao_exact(Nullable<System.DateTime> ngaytao_tu, Nullable<System.DateTime> ngaytao_den, Nullable<int> nhaNao)
        {
            var ngaytao_tuParameter = ngaytao_tu.HasValue ?
                new ObjectParameter("ngaytao_tu", ngaytao_tu) :
                new ObjectParameter("ngaytao_tu", typeof(System.DateTime));
    
            var ngaytao_denParameter = ngaytao_den.HasValue ?
                new ObjectParameter("ngaytao_den", ngaytao_den) :
                new ObjectParameter("ngaytao_den", typeof(System.DateTime));
    
            var nhaNaoParameter = nhaNao.HasValue ?
                new ObjectParameter("NhaNao", nhaNao) :
                new ObjectParameter("NhaNao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<qlchiphi_select_item_ngaytao_exact_Result>("qlchiphi_select_item_ngaytao_exact", ngaytao_tuParameter, ngaytao_denParameter, nhaNaoParameter);
        }
    }
}
