//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quan_Ly_Chi_Phi
    {
        public long ID { get; set; }
        public Nullable<decimal> So_Tien_Chi_Phi { get; set; }
        public string Ghi_Chu { get; set; }
        public Nullable<int> Nha_Nao { get; set; }
        public Nullable<System.DateTime> Ngay_Nhap_Chi_Phi { get; set; }
        public string Nguoi_Nhap { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
    }
}
