//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class VIDEO
    {
        public long ID { get; set; }
        public Nullable<long> ID_VIDEO { get; set; }
        public string VIDEO_URL { get; set; }
        public string MAIN_HOVER_TEXT { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
    }
}
